### PR TITLE
Specified attribute `encoding` to "UTF-8" when creating instance of xmlB...

### PR DESCRIPTION
**Pull request by mathieug**
...uilder

### CODE REVIEW

**Comment by BenjaminN** [comment]
:+1:

**Comment by mathieug** [comment]
@baalexander @patricklodder

**Comment by patricklodder** [comment]
@mathieug Sorry, this is taking some time because I cannot merge this as-is. The XMLRPC spec leaves encoding open to implementation so we cannot start hard-coding UTF-8 as that might break implementations other than yours. We'll need to make this configurable and optional.

**Comment by mathieug** [comment]
@patricklodder Any news?

**Pull request closed without merging**
